### ISSUE TITLE
Nothing happens on running the .bat file

### ISSUE THREAD

**Issue by akgcode** [leocd91/autoscreenshotpy#1]

**Comment by leocd91** [comment]
hi, can you run the bat from the command prompt and see what the error was?

**Comment by akgcode** [comment]
hey, appreciate the prompt reply.
on running that .bat file, command prompt window blinked for a few milisec. Nothing else happened.
Run on windows 10.

**Comment by leocd91** [comment]
I mean can you open the command prompt first, then run the program, for example "C:\Downloads\run_auto_screenshot.bat" then press enter to run it and see the error?

cool, thank you for submitting the issue too..

**Comment by akgcode** [comment]
update, on running from cmd, the cmd window exits. Nothing else.
thanks for looking into this!
